"""
Core Intelligence Substrate Components

Provides the foundational architecture for the intelligence substrate,
including base classes and interfaces for cognitive modules.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum
import time


class CognitiveState(Enum):
    """States of cognitive processing"""
    IDLE = "idle"
    PROCESSING = "processing"
    LEARNING = "learning"
    REASONING = "reasoning"
    COORDINATING = "coordinating"


@dataclass
class Thought:
    """Represents a unit of cognitive processing"""
    content: Any
    timestamp: float = field(default_factory=time.time)
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)
    source_module: Optional[str] = None


class CognitiveModule(ABC):
    """
    Abstract base class for all cognitive modules in the substrate.
    
    Cognitive modules are specialized components that handle specific
    aspects of intelligence (reasoning, memory, learning, etc.)
    """
    
    def __init__(self, name: str):
        self.name = name
        self.state = CognitiveState.IDLE
        self.performance_metrics: Dict[str, float] = {}
    
    @abstractmethod
    def process(self, input_data: Any) -> Thought:
        """Process input and generate a thought"""
        pass
    
    @abstractmethod
    def update(self, feedback: Dict[str, Any]) -> None:
        """Update module based on feedback"""
        pass
    
    def get_state(self) -> CognitiveState:
        """Get current state of the module"""
        return self.state
    
    def get_metrics(self) -> Dict[str, float]:
        """Get performance metrics"""
        return self.performance_metrics.copy()


class IntelligenceSubstrate:
    """
    Main intelligence substrate that coordinates cognitive modules.
    
    This is the central orchestrator that manages the flow of information
    between different cognitive components and maintains the overall
    system state.
    """
    
    def __init__(self, name: str = "ASI-Substrate"):
        self.name = name
        self.modules: Dict[str, CognitiveModule] = {}
        self.thought_stream: List[Thought] = []
        self.global_state = CognitiveState.IDLE
        self._context: Dict[str, Any] = {}
    
    def register_module(self, module: CognitiveModule) -> None:
        """Register a cognitive module with the substrate"""
        if module.name in self.modules:
            raise ValueError(f"Module {module.name} already registered")
        self.modules[module.name] = module
    
    def unregister_module(self, module_name: str) -> None:
        """Unregister a cognitive module"""
        if module_name in self.modules:
            del self.modules[module_name]
    
    def process_input(self, input_data: Any, target_module: Optional[str] = None) -> List[Thought]:
        """
        Process input through the substrate.
        
        Args:
            input_data: The input to process
            target_module: Optional specific module to use, otherwise all modules
        
        Returns:
            List of thoughts generated by modules
        """
        self.global_state = CognitiveState.PROCESSING
        thoughts = []
        
        try:
            if target_module:
                if target_module not in self.modules:
                    raise ValueError(f"Module {target_module} not found")
                thought = self.modules[target_module].process(input_data)
                thoughts.append(thought)
            else:
                # Process through all modules
                for module in self.modules.values():
                    thought = module.process(input_data)
                    thoughts.append(thought)
            
            # Add to thought stream
            self.thought_stream.extend(thoughts)
            
            return thoughts
        finally:
            self.global_state = CognitiveState.IDLE
    
    def get_thought_stream(self, limit: Optional[int] = None) -> List[Thought]:
        """Get recent thoughts from the stream"""
        if limit:
            return self.thought_stream[-limit:]
        return self.thought_stream.copy()
    
    def clear_thought_stream(self) -> None:
        """Clear the thought stream"""
        self.thought_stream.clear()
    
    def set_context(self, key: str, value: Any) -> None:
        """Set a context value"""
        self._context[key] = value
    
    def get_context(self, key: str, default: Any = None) -> Any:
        """Get a context value"""
        return self._context.get(key, default)
    
    def get_module(self, module_name: str) -> Optional[CognitiveModule]:
        """Get a specific module by name"""
        return self.modules.get(module_name)
    
    def get_all_modules(self) -> Dict[str, CognitiveModule]:
        """Get all registered modules"""
        return self.modules.copy()
    
    def get_system_status(self) -> Dict[str, Any]:
        """Get overall system status"""
        return {
            "name": self.name,
            "state": self.global_state.value,
            "modules": {
                name: {
                    "state": module.get_state().value,
                    "metrics": module.get_metrics()
                }
                for name, module in self.modules.items()
            },
            "thought_stream_size": len(self.thought_stream),
            "context_keys": list(self._context.keys())
        }
